name: aivellum
description: AI Prompts Collection App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^12.1.3

  # UI/UX
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  flutter_staggered_animations: ^1.1.1

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Monetization
  google_mobile_ads: ^4.0.0
  in_app_purchase: ^3.1.11

  # HTTP & JSON
  http: ^1.1.0
  json_annotation: ^4.8.1

  # Utilities
  uuid: ^4.2.1
  intl: ^0.20.2
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/data/
    - assets/icons/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf